# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Start with the base Python image
FROM python:3.11-slim-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the project files into the container
COPY . .

# Install the necessary dependencies
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Set the environment variable for the Rememberizer API token
# It is recommended to set this as a secret in production environments
ENV REMEMBERIZER_API_TOKEN=your_rememberizer_api_token

# The command to run your application
ENTRYPOINT ["python", "-m", "mcp_server_rememberizer.server"]
